import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./modules/**/*.{js,ts,jsx,tsx,mdx}",
    "./shared/**/*.{js,ts,jsx,tsx,mdx}",
    "./exp/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-atkinson)", "system-ui", "sans-serif"],
        serif: ["var(--font-source-serif)", "Georgia", "serif"],
        // Stitch classes usually prefix font family like font-headline-md
        "headline-xl": ["var(--font-source-serif)", "Georgia", "serif"],
        "headline-lg": ["var(--font-source-serif)", "Georgia", "serif"],
        "headline-md": ["var(--font-source-serif)", "Georgia", "serif"],
        "body-lg": ["var(--font-atkinson)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-atkinson)", "system-ui", "sans-serif"],
        "label-md": ["var(--font-atkinson)", "system-ui", "sans-serif"],
        "label-sm": ["var(--font-atkinson)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      spacing: {
        "base": "8px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      colors: {
        "surface": "#fbf9f8",
        "surface-dim": "#dbd9d9",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e2",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#44474d",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f2f0f0",
        "outline": "#75777e",
        "outline-variant": "#c5c6ce",
        "surface-tint": "#4f5f7b",
        "primary": "#04162e",
        "on-primary": "#ffffff",
        "primary-container": "#1a2b44",
        "on-primary-container": "#8292b0",
        "inverse-primary": "#b6c7e7",
        "secondary": "#4b6455",
        "on-secondary": "#ffffff",
        "secondary-container": "#cae6d4",
        "on-secondary-container": "#4f6859",
        "tertiary": "#161714",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2a2b28",
        "on-tertiary-container": "#93928e",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#b6c7e7",
        "on-primary-fixed": "#091c34",
        "on-primary-fixed-variant": "#374762",
        "secondary-fixed": "#cde9d6",
        "secondary-fixed-dim": "#b1cdbb",
        "on-secondary-fixed": "#072014",
        "on-secondary-fixed-variant": "#344c3e",
        "tertiary-fixed": "#e4e2dd",
        "tertiary-fixed-dim": "#c8c6c2",
        "on-tertiary-fixed": "#1b1c19",
        "on-tertiary-fixed-variant": "#474744",
        "background": "#fbf9f8",
        "on-background": "#1b1c1c",
      },
    },
  },
  plugins: [],
};
export default config;
