const fs = require('fs');
const path = require('path');

const CSS_FILES = {
  spacing: path.join(__dirname, '../styles/foundation/spacing.css'),
  radius: path.join(__dirname, '../styles/foundation/radius.css'),
  zIndex: path.join(__dirname, '../styles/foundation/z-index.css'),
  motion: path.join(__dirname, '../styles/foundation/motion.css')
};

const OUTPUT_FILE = path.join(__dirname, '../modules/shared/ui/tokens.ts');

function parseCssVariables(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const regex = /--([\w-]+):\s*([^;]+);/g;
  const tokens = {};
  let match;
  while ((match = regex.exec(content)) !== null) {
    const key = match[1];
    const val = match[2].trim();
    tokens[key] = val;
  }
  return tokens;
}

function camelCase(str) {
  return str.replace(/-([a-z0-9])/g, (g) => g[1].toUpperCase());
}

function formatTokensGroup(tokens) {
  const formatted = {};
  for (const [key, val] of Object.entries(tokens)) {
    // Strip group prefixes to make keys cleaner (e.g. space-1 -> 1, radius-sm -> sm, z-base -> base)
    const cleanedKey = key
      .replace(/^space-/, '')
      .replace(/^radius-/, '')
      .replace(/^z-/, '')
      .replace(/^duration-/, '')
      .replace(/^ease-/, '');
    
    // Parse numeric values where possible for runtime arithmetic
    const numVal = parseFloat(val);
    if (!isNaN(numVal) && (val.endsWith('px') || val.endsWith('rem') || val.endsWith('ms') || !val.match(/[a-zA-Z]/))) {
      formatted[cleanedKey] = val;
    } else {
      formatted[cleanedKey] = val;
    }
  }
  return formatted;
}

function generate() {
  const spacingRaw = parseCssVariables(CSS_FILES.spacing);
  const radiusRaw = parseCssVariables(CSS_FILES.radius);
  const zIndexRaw = parseCssVariables(CSS_FILES.zIndex);
  const motionRaw = parseCssVariables(CSS_FILES.motion);

  const spacing = formatTokensGroup(spacingRaw);
  const radius = formatTokensGroup(radiusRaw);
  const zIndex = formatTokensGroup(zIndexRaw);
  const motion = formatTokensGroup(motionRaw);

  const code = `// Automatically generated design tokens from CSS foundations.
// Do not edit this file manually.

export const spacing = ${JSON.stringify(spacing, null, 2)} as const;

export const radius = ${JSON.stringify(radius, null, 2)} as const;

export const zIndex = ${JSON.stringify(zIndex, null, 2)} as const;

export const motion = ${JSON.stringify(motion, null, 2)} as const;
`;

  const dir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(OUTPUT_FILE, code, 'utf-8');
  console.log(`Successfully generated tokens at ${OUTPUT_FILE}`);
}

generate();
