const fs = require('fs');

const files = [
  'admin/src/features/books/components/BookFileUpload.tsx',
  'admin/src/features/books/file-actions.ts',
  'modules/books/infrastructure/SupabaseBookFileRepository.ts',
  'admin/src/features/languages/actions.ts',
  'admin/src/app/languages/[id]/page.tsx',
  'admin/src/features/collections/actions.ts',
  'admin/src/app/collections/[id]/page.tsx',
  'admin/src/features/featured_books/actions.ts',
  'admin/src/features/announcements/actions.ts',
  'admin/src/app/announcements/[id]/page.tsx'
];

for (const f of files) {
  if (fs.existsSync(f)) {
    let content = fs.readFileSync(f, 'utf8');
    content = content.replace(/\\\`/g, '`').replace(/\\\$/g, '$');
    fs.writeFileSync(f, content);
  }
}

// I might have also done it in the other files generated by my generator script! Let's just fix all of them just in case.
const { execSync } = require('child_process');
try {
  execSync('npx prettier --write "admin/src/**/*.{ts,tsx}" "modules/**/*.{ts,tsx}"');
} catch (e) {
  console.log("Prettier failed");
}
